"load color scheme with syntax
syntax enable
set background=dark
colorscheme solarized

set number "show line numbers

set hlsearch "highlight search

call pathogen#infect()

filetype plugin indent on
