"load color scheme with syntax
syntax enable
set background=dark
colorscheme solarized

set number "show line numbers
set cpoptions+=$
set hlsearch "highlight search
set expandtab
set tabstop=2 shiftwidth=2 softtabstop=2
set autoindent

call pathogen#infect()

filetype plugin indent on

inoremap <expr> <C-Space> pumvisible() ? '<C-n>' : '<C-x><C-o><C-n><C-p><C-r>=pumvisible() ? "\<lt>Down>" : ""<CR>'
imap <S-CR>    <CR><CR>end<Esc>-cc
nmap <F8> :TagbarToggle<CR>
nmap <F7> :NERDTreeToggle<CR>
if has("autocmd") 
  autocmd Filetype java setlocal omnifunc=javacomplete#Complete 
endif 
