#source the configuration of the path
source "$HOME/Development/dots/bash/conf/path"

#source the configuration of the aliases
source "$HOME/Development/dots/bash/conf/aliases"

#source the configuration of the functions
source "$HOME/Development/dots/bash/conf/functions"

#source general configuration
source "$HOME/Development/dots/bash/conf/general"

#source rvm configuration
source "$HOME/Development/dots/bash/conf/rvm"

#source bash_completion configuration
source "$HOME/Development/dots/bash/conf/bash_completion"

#source bash_profileDevelopment/local if it exists
if [ -e "$HOME/Development/bash_profileDevelopment/local" ]; then
  source "$HOME/Development/bash_profileDevelopment/local"
fi
